---

- name: Provide etcd inventory
  copy:
    src: openstack-ansible/playbooks/inventory_fds/env.d/etcd.yml
    dest: "{{openstack_osa_path}}/inventory/env.d/etcd.yml"

- name: copy openstack_user_config
  copy:
    src: "{{XCI_FLAVOR}}/openstack_user_config.yml"
    dest: "{{openstack_osa_etc_path}}/openstack_user_config.yml"

- name: copy ansible role requirements
  copy:
    src: "ansible-role-requirements.yml"
    dest: "{{openstack_osa_path}}//ansible-role-requirements.yml"

- name: copy user_vpp_scenario_variables
  copy:
    src: "user_variables_os-nosdn-fds.yml"
    dest: "{{openstack_osa_etc_path}}/user_variables_os-nosdn-fds.yml"

