---
component_skel:
  etcd:
    belongs_to:
      - etcd_all

container_skel:
  etcd_container:
    belongs_to:
      - etcd_containers
      - shared-infra_containers
    contains:
      - etcd

physical_skel:
  etcd_containers:
    belongs_to:
      - all_containers
  etcd_hosts:
    belongs_to:
      - hosts
